### ISSUE TITLE
I builds a strange tree with my regex

### ISSUE THREAD

**Issue by Dhurgan** [Jcparkyn/nodexr#116]
I came here because I saw your old post on reddit and wanted to se how you solved the nodes in your solution, trying to teach myself how it works before I give it a go...
I tested one of my commonly used regex in your website and it came up with some problems... 
Just wanted you to see how it looks...
regex is `^[A-Z]([A-Z0-9]\d{3}[A-Z0-9])(A\d{2}|A|D|E)$`
basically it's a verification of sorts...
But it gave the wrong output... no worries for my part but I though you might want to know...
![not-quite-right](https://user-images.githubusercontent.com/80201201/110238994-e451c580-7f44-11eb-941a-e5fcb34fd114.PNG)

**Comment by Dhurgan** [comment]
if you add a questionmark after the last capture so it becomes optional, it does things a bit different but still seems confused.

**Comment by Jcparkyn** [comment]
That's interesting, it looks like some of the nodes just aren't being rendered properly.
That regex works fine for me; what browser are you using?

Unless it's some browser-specific bug, I think it could most likely be due to the way the positions of the nodes are being formatted based on locale. Would you mind telling me what country/locale you're in?

**Comment by Dhurgan** [comment]
Google Chrome Version 89.0.4389.90 (Officiell version) (64 bitar)
Normaly Swedish as first language, tried switching it to US English as first prio but the result is the same...
Just checked with Microsoft Edge Version 89.0.774.54 (Officiell version) (64 bitar), and there it looks ok.
Funny though since I though Edge is using the same rendering engine as Chrome?

**Comment by Jcparkyn** [comment]
I've narrowed down the problem to the Swedish locale (sv-se) and the way that it formats negative numbers. It uses a different type of dash for the minus sign in the positions of the nodes, which CSS doesn't understand. I'm guessing that when you changed the language to US English, either the locale used by chrome didn't change, or you didn't refresh the page.

Thanks for reporting, and a fix should be coming soon.

**Comment by Jcparkyn** [comment]
Fixed in release v1.4.2.
